import { AuditTarget } from "../components/ex-columns"

export async function getData(): Promise<AuditTarget[]> {
  return [
    {
      id: "728ed52f",
      rawMaterialName: "SLA BATTERY 12V/12AH",
      jobNo: "A240008",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 4",
      uom: "set",
      sapQty: 23,
      physicalQty: 23,
      discrepancy: 0,
      status: "matched",
      lastVerified: "23 Oct 2024",
    },
    {
      id: "489e1d42",
      rawMaterialName: "TYRE 14 X 2.50",
      jobNo: "A240008",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Bahan Baku 1",
      uom: "pcs",
      sapQty: 100,
      physicalQty: 95,
      discrepancy: -5,
      status: "sap-discrepancy",
      lastVerified: "24 Oct 2024",
    },
    {
      id: "9b1c8f7a",
      rawMaterialName: "BLDC MOTOR 500W",
      jobNo: "A240009",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 50,
      physicalQty: 50,
      discrepancy: 0,
      status: "matched",
      lastVerified: "25 Oct 2024",
    },
    {
      id: "a3f5c219",
      rawMaterialName: "BRAKE LEVER ASSY",
      jobNo: "A240010",
      fgName: "E-SCOOTER PRO MAX",
      warehouse: "Gudang Perakitan",
      uom: "set",
      sapQty: 120,
      physicalQty: 0,
      discrepancy: -120,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "f82d1c34",
      rawMaterialName: "LED HEADLIGHT 12V",
      jobNo: "A240009",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 45,
      physicalQty: 46,
      discrepancy: 1,
      status: "blind-mismatch",
      lastVerified: "26 Oct 2024",
    },
    {
      id: "e4a7b901",
      rawMaterialName: "CHARGER 48V/12AH",
      jobNo: "A240008",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 4",
      uom: "pcs",
      sapQty: 75,
      physicalQty: 75,
      discrepancy: 0,
      status: "counting",
      lastVerified: "26 Oct 2024",
    },
    {
      id: "c5d8e23f",
      rawMaterialName: "THROTTLE GRIP",
      jobNo: "A240011",
      fgName: "E-SCOOTER MINI",
      warehouse: "Gudang Bahan Baku 2",
      uom: "set",
      sapQty: 150,
      physicalQty: 150,
      discrepancy: 0,
      status: "matched",
      lastVerified: "27 Oct 2024",
    },
    {
      id: "b6f1a842",
      rawMaterialName: "REAR SHOCK ABSORBER",
      jobNo: "A240008",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Perakitan",
      uom: "pcs",
      sapQty: 80,
      physicalQty: 82,
      discrepancy: 2,
      status: "sap-discrepancy",
      lastVerified: "27 Oct 2024",
    },
    {
      id: "d9e3c1a5",
      rawMaterialName: "STEEL FRAME 14 INCH",
      jobNo: "A240012",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Utama",
      uom: "pcs",
      sapQty: 30,
      physicalQty: 0,
      discrepancy: -30,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "1a2b3c4d",
      rawMaterialName: "IGNITION KEY SET",
      jobNo: "A240009",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 2",
      uom: "set",
      sapQty: 60,
      physicalQty: 58,
      discrepancy: -2,
      status: "blind-mismatch",
      lastVerified: "28 Oct 2024",
    },
    {
      id: "3e5d7a9b",
      rawMaterialName: "FRONT FORK SUSPENSION",
      jobNo: "A240015",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Perakitan",
      uom: "set",
      sapQty: 40,
      physicalQty: 40,
      discrepancy: 0,
      status: "matched",
      lastVerified: "28 Oct 2024",
    },
    {
      id: "8c2f4e1d",
      rawMaterialName: "DIGITAL SPEEDOMETER DISPLAY",
      jobNo: "A240016",
      fgName: "E-SCOOTER PRO MAX",
      warehouse: "Sortasi 1",
      uom: "pcs",
      sapQty: 15,
      physicalQty: 12,
      discrepancy: -3,
      status: "sap-discrepancy",
      lastVerified: "28 Oct 2024",
    },
    {
      id: "5a9b3c7f",
      rawMaterialName: "PEDAL ASSIST SENSOR (PAS)",
      jobNo: "A240015",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 3",
      uom: "pcs",
      sapQty: 100,
      physicalQty: 100,
      discrepancy: 0,
      status: "counting",
      lastVerified: "29 Oct 2024",
    },
    {
      id: "d1e8f2a4",
      rawMaterialName: "KICKSTAND 14 INCH",
      jobNo: "A240018",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Gudang Bahan Baku 2",
      uom: "pcs",
      sapQty: 200,
      physicalQty: 0,
      discrepancy: -200,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "7f4c9b1e",
      rawMaterialName: "SADDLE SEAT PU LEATHER",
      jobNo: "A240018",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 55,
      physicalQty: 56,
      discrepancy: 1,
      status: "blind-mismatch",
      lastVerified: "29 Oct 2024",
    },
    {
      id: "2a6d5f8c",
      rawMaterialName: "DISC BRAKE PAD",
      jobNo: "A240019",
      fgName: "E-SCOOTER MINI",
      warehouse: "Gudang Utama",
      uom: "set",
      sapQty: 300,
      physicalQty: 300,
      discrepancy: 0,
      status: "matched",
      lastVerified: "29 Oct 2024",
    },
    {
      id: "b4e1c7a9",
      rawMaterialName: "WIRING HARNESS 48V",
      jobNo: "A240020",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Perakitan",
      uom: "set",
      sapQty: 85,
      physicalQty: 80,
      discrepancy: -5,
      status: "sap-discrepancy",
      lastVerified: "30 Oct 2024",
    },
    {
      id: "9f3a1d6b",
      rawMaterialName: "REARVIEW MIRROR SET",
      jobNo: "A240020",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 4",
      uom: "set",
      sapQty: 150,
      physicalQty: 0,
      discrepancy: -150,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "c8b2e5f1",
      rawMaterialName: "CHAIN 114L",
      jobNo: "A240022",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Gudang Bahan Baku 1",
      uom: "pcs",
      sapQty: 90,
      physicalQty: 90,
      discrepancy: 0,
      status: "counting",
      lastVerified: "30 Oct 2024",
    },
    {
      id: "1d7f4a2c",
      rawMaterialName: "PLASTIC FENDER FRONT/REAR",
      jobNo: "A240022",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 3",
      uom: "set",
      sapQty: 110,
      physicalQty: 115,
      discrepancy: 5,
      status: "blind-mismatch",
      lastVerified: "31 Oct 2024",
    },
    {
      id: "4f2a9c1b",
      rawMaterialName: "WHEEL HUB MOTOR 350W",
      jobNo: "A240023",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Gudang Utama",
      uom: "pcs",
      sapQty: 80,
      physicalQty: 80,
      discrepancy: 0,
      status: "matched",
      lastVerified: "01 Nov 2024",
    },
    {
      id: "7e8b3d2f",
      rawMaterialName: "LITHIUM BATTERY 48V/20AH",
      jobNo: "A240023",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Sortasi 1",
      uom: "set",
      sapQty: 45,
      physicalQty: 42,
      discrepancy: -3,
      status: "sap-discrepancy",
      lastVerified: "01 Nov 2024",
    },
    {
      id: "1a5c9e4d",
      rawMaterialName: "ALUMINUM ALLOY RIM 14 INCH",
      jobNo: "A240024",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Bahan Baku 1",
      uom: "pcs",
      sapQty: 120,
      physicalQty: 125,
      discrepancy: 5,
      status: "blind-mismatch",
      lastVerified: "01 Nov 2024",
    },
    {
      id: "9b3f4a1c",
      rawMaterialName: "CONTROLLER MODULE 48V",
      jobNo: "A240025",
      fgName: "E-SCOOTER PRO MAX",
      warehouse: "Gudang Perakitan",
      uom: "pcs",
      sapQty: 60,
      physicalQty: 60,
      discrepancy: 0,
      status: "counting",
      lastVerified: "02 Nov 2024",
    },
    {
      id: "2d7e1f5a",
      rawMaterialName: "TAILLIGHT ASSEMBLY",
      jobNo: "A240026",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 3",
      uom: "set",
      sapQty: 200,
      physicalQty: 0,
      discrepancy: -200,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "8c1a2b3d",
      rawMaterialName: "HORN / BUZZER 12V",
      jobNo: "A240026",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 150,
      physicalQty: 150,
      discrepancy: 0,
      status: "matched",
      lastVerified: "02 Nov 2024",
    },
    {
      id: "5f4e9d8c",
      rawMaterialName: "BRAKE CABLE FRONT",
      jobNo: "A240027",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Gudang Utama",
      uom: "pcs",
      sapQty: 300,
      physicalQty: 290,
      discrepancy: -10,
      status: "sap-discrepancy",
      lastVerified: "02 Nov 2024",
    },
    {
      id: "3b2a1c4d",
      rawMaterialName: "BRAKE CABLE REAR",
      jobNo: "A240027",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Gudang Utama",
      uom: "pcs",
      sapQty: 300,
      physicalQty: 310,
      discrepancy: 10,
      status: "blind-mismatch",
      lastVerified: "03 Nov 2024",
    },
    {
      id: "e1f2a3b4",
      rawMaterialName: "HANDLEBAR GRIP RUBBER",
      jobNo: "A240028",
      fgName: "E-SCOOTER MINI",
      warehouse: "Sortasi 4",
      uom: "set",
      sapQty: 400,
      physicalQty: 400,
      discrepancy: 0,
      status: "counting",
      lastVerified: "03 Nov 2024",
    },
    {
      id: "6d5c4b3a",
      rawMaterialName: "CHARGER PORT CONNECTOR",
      jobNo: "A240029",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Gudang Bahan Baku 2",
      uom: "pcs",
      sapQty: 180,
      physicalQty: 0,
      discrepancy: -180,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "a1b2c3d4",
      rawMaterialName: "BASKET PLASTIC FRONT",
      jobNo: "A240030",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Sortasi 1",
      uom: "pcs",
      sapQty: 85,
      physicalQty: 85,
      discrepancy: 0,
      status: "matched",
      lastVerified: "04 Nov 2024",
    },
    {
      id: "f4e3d2c1",
      rawMaterialName: "BASKET MOUNTING BRACKET",
      jobNo: "A240030",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Sortasi 1",
      uom: "set",
      sapQty: 85,
      physicalQty: 83,
      discrepancy: -2,
      status: "sap-discrepancy",
      lastVerified: "04 Nov 2024",
    },
    {
      id: "c9b8a7d6",
      rawMaterialName: "REFLECTOR REAR RED",
      jobNo: "A240031",
      fgName: "E-SCOOTER PRO MAX",
      warehouse: "Gudang Perakitan",
      uom: "pcs",
      sapQty: 250,
      physicalQty: 252,
      discrepancy: 2,
      status: "blind-mismatch",
      lastVerified: "04 Nov 2024",
    },
    {
      id: "2e3f4a5b",
      rawMaterialName: "STEERING COLUMN TUBE",
      jobNo: "A240032",
      fgName: "E-SCOOTER MINI",
      warehouse: "Gudang Utama",
      uom: "pcs",
      sapQty: 110,
      physicalQty: 110,
      discrepancy: 0,
      status: "counting",
      lastVerified: "05 Nov 2024",
    },
    {
      id: "d5c6b7a8",
      rawMaterialName: "FOLDING MECHANISM LATCH",
      jobNo: "A240032",
      fgName: "E-SCOOTER MINI",
      warehouse: "Gudang Bahan Baku 1",
      uom: "set",
      sapQty: 110,
      physicalQty: 0,
      discrepancy: -110,
      status: "pending",
      lastVerified: "-",
    },
    {
      id: "7a8b9c0d",
      rawMaterialName: "WHEEL AXLE NUT 14MM",
      jobNo: "A240033",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 600,
      physicalQty: 600,
      discrepancy: 0,
      status: "matched",
      lastVerified: "05 Nov 2024",
    },
    {
      id: "1f2e3d4c",
      rawMaterialName: "WHEEL AXLE WASHER",
      jobNo: "A240033",
      fgName: "E-BIKE 14 X 2.50 EXOTIC EV-922",
      warehouse: "Sortasi 2",
      uom: "pcs",
      sapQty: 1200,
      physicalQty: 1190,
      discrepancy: -10,
      status: "sap-discrepancy",
      lastVerified: "05 Nov 2024",
    },
    {
      id: "8d9c0b1a",
      rawMaterialName: "SEAT POST ALLOY 27.2MM",
      jobNo: "A240034",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Gudang Perakitan",
      uom: "pcs",
      sapQty: 70,
      physicalQty: 71,
      discrepancy: 1,
      status: "blind-mismatch",
      lastVerified: "06 Nov 2024",
    },
    {
      id: "b1c2d3e4",
      rawMaterialName: "SEAT POST CLAMP",
      jobNo: "A240034",
      fgName: "E-BIKE 14 X 2.50 PACIFIC SYNC",
      warehouse: "Gudang Perakitan",
      uom: "pcs",
      sapQty: 70,
      physicalQty: 70,
      discrepancy: 0,
      status: "counting",
      lastVerified: "06 Nov 2024",
    },
    {
      id: "4e5f6a7b",
      rawMaterialName: "MUDGUARD BRACKET STEEL",
      jobNo: "A240035",
      fgName: "E-BIKE UWINFLY DF7",
      warehouse: "Sortasi 3",
      uom: "set",
      sapQty: 130,
      physicalQty: 0,
      discrepancy: -130,
      status: "pending",
      lastVerified: "-",
    },
  ]
}
